In [20]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [21]:
df=pd.read_csv('E:\\data sets dowload\\Iris(2).csv')

In [22]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [23]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [24]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [25]:
df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)

In [26]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [27]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [28]:
x.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [29]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int32

# beginging splitting

In [30]:
import sklearn

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.33, random_state=42)

In [33]:
print(len(X_train))
print(len(y_train))

100
100


# importing model

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
reg=LogisticRegression()  

In [37]:
reg.fit(X_train,y_train)

C:\Users\RGUKT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [38]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [39]:
ypred=reg.predict(X_train)

# finding accuracy

In [41]:
#accuracy of trainigng
accuracy_score(y_train,ypred)

1.0

In [45]:
#confusion matrix
confusion_matrix(y_train,ypred)

array([[31,  0,  0],
       [ 0, 35,  0],
       [ 0,  0, 34]], dtype=int64)

In [47]:
#classification report
print(classification_report(y_train,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [48]:
#doing for test data

In [49]:
X_test.shape

(50, 5)

In [50]:
ypredtest=reg.predict(X_test)

In [ ]:
#testing accuracy for test data

In [51]:
accuracy_score(y_test,ypredtest)

1.0

In [52]:
confusion_matrix(y_test,ypredtest)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 16]], dtype=int64)

In [53]:
print(classification_report(y_test,ypredtest))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



In [54]:
#training and testing completed

In [55]:
#Checking with models 

In [56]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [57]:
c=[]
for i in df.iloc[1,0:-1]:
    c.append(i)
print(c)

[2.0, 4.9, 3.0, 1.4, 0.2]


In [59]:
a=reg.predict([c])

C:\Users\RGUKT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [60]:
#for checking difference btw a[0] and a
print(a)


[0]


In [61]:
print(a[0])

0


In [62]:
#checking with real time
cc=[]
for i in range(5):
    cc.append(i)
print(cc)

[0, 1, 2, 3, 4]


In [63]:
df['Species'].unique()#  ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

array([0, 1, 2])

In [64]:
v=reg.predict([c])
v1=v[0]
if v1==0:
    print('Iris-setosa')
elif v1==1:
    print('Iris-versicolor')
else:
    print('Iris-virginica')

Iris-setosa


C:\Users\RGUKT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
